apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: rag-backend
  name: rag-backend
  namespace: default

spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10

  selector:
    matchLabels:
      app: rag-backend

  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: rag-backend

    spec:
      containers:
      - name: newimage
        image: us-central1-docker.pkg.dev/lexical-aileron-483517-f3/rag-backend/rag_backend:v1
        imagePullPolicy: Always

        # Mount configmap to /app
        volumeMounts:
        - name: db-config-volume
          mountPath: /app/config.json
          subPath: config.json
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File

      # Define the volume from ConfigMap
      volumes:
      - name: db-config-volume
        configMap:
          name: db-config

      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
