apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  labels:
    app: rag-backend
  name: rag-backend
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.227.2
  clusterIPs:
  - 34.118.227.2
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 30792
    port: 8001
    protocol: TCP
    targetPort: 8001
  selector:
    app: rag-backend
  sessionAffinity: None
  type: LoadBalancer
