name: Deploy MLFlow Server

on:
  workflow_dispatch:

jobs:
  login-build-push:
    name: Build, Push and Deploy
    runs-on: ubuntu-latest

    env:
      REGION: us-central1
      PROJECT_ID: daring-night-479819-f3
      REPOSITORY: mlflow
      SERVICE_ACCOUNT: mlflow-server-account@daring-night-479819-f3.iam.gserviceaccount.com
      SERVICE_NAME: mlflow-server

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build container
        run: |
          docker build \
            -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/mlflow:${{ github.sha }}" \
            -f Infra/mlflow/Dockerfile \
            Infra/mlflow

      - name: Push container
        run: |
          docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/mlflow:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy "${{ env.SERVICE_NAME }}" \
            --image "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/mlflow:${{ github.sha }}" \
            --region "${{ env.REGION }}" \
            --service-account "${{ env.SERVICE_ACCOUNT }}" \
            --update-secrets=/secrets/credentials=access_keys:latest \
            --update-secrets=POSTGRESQL_URL=database_url:latest \
            --update-secrets=STORAGE_URL=bucket_url:latest \
            --memory 2Gi \
            --port 8080 \
            --allow-unauthenticated
